import { collection, addDoc, query, orderBy, onSnapshot, serverTimestamp, doc, deleteDoc } from 'firebase/firestore';

export const createNotificationSlice = (set, get) => ({
  // State
  toast: {
    visible: false,
    message: '',
    type: 'info',
  },
  toastHistory: [],
  unsubscribeNotifications: null,
  hasUnreadNotifications: false,
  lastCheckedNotifications: null,

  // Actions
  deleteNotification: async (notificationId) => {
    const user = get().user;
    if (!user) return;

    // With the corrected data flow, this check is a final safeguard.
    // The ID should always be a valid string from Firestore.
    if (typeof notificationId !== 'string' || !notificationId) {
        console.error("Delete failed: Invalid notificationId provided.", notificationId);
        get().showToast("Failed to delete notification due to an invalid ID.", "error");
        return;
    }

    try {
        const notificationRef = doc(get().db, "users", user.uid, "notifications", notificationId);
        await deleteDoc(notificationRef);
    } catch (error) {
        console.error("Error deleting notification from Firestore:", error);
        get().showToast("Failed to delete notification.", "error");
    }
  },
  
  showToast: (message, type = 'info') => {
    // Step 1: Immediately show the temporary, pop-up toast message.
    set({ toast: { id: Date.now(), message, type, visible: true } });

    // Step 2: Save the notification to Firestore. The `onSnapshot` listener in `loadNotifications`
    // is the ONLY mechanism that will update the persistent `toastHistory` list in the UI.
    const dataToSave = { message, type, createdAt: serverTimestamp() };
    get().saveNotification(dataToSave); 

    // Step 3: Hide the pop-up toast after a delay.
    setTimeout(() => set(state => ({ toast: { ...state.toast, visible: false } })), 3000);
  },

  saveNotification: async (toastData) => {
    const user = get().user;
    if (!user) return;
    try {
      const notificationsCollection = collection(get().db, "users", user.uid, "notifications");
      await addDoc(notificationsCollection, toastData);
    } catch (error) {
      console.error("Error saving notification to Firestore:", error);
    }
  },

  loadNotifications: (userId) => {
    const q = query(collection(get().db, "users", userId, "notifications"), orderBy("createdAt", "desc"));
    const unsubscribe = onSnapshot(q, (snapshot) => {
      // This is now the single source of truth for the notification list.
      // `doc.id` is always a string generated by Firestore.
      const notifications = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
      const lastChecked = get().lastCheckedNotifications;
      const hasUnread = notifications.some(n => n.createdAt?.toDate().getTime() > lastChecked);
      set({ toastHistory: notifications, hasUnreadNotifications: hasUnread });
    }, (error) => {
        console.error("Error listening to notification changes:", error);
    });
    set({ unsubscribeNotifications: unsubscribe });
    
    const lastChecked = localStorage.getItem(`lastChecked_${userId}`);
    set({ lastCheckedNotifications: lastChecked ? parseInt(lastChecked, 10) : Date.now() });
  },
  
  handleEvents: (events) => {
      if (!events || !Array.isArray(events)) return;
      events.forEach(event => {
        if (event.type === 'toast') {
          get().showToast(event.message, event.toastType);
        }
      });
  },
  
  closeNotificationModal: () => {
    const userId = get().user?.uid;
    const now = Date.now();
    set({ isNotificationModalOpen: false, hasUnreadNotifications: false, lastCheckedNotifications: now });
    if(userId) {
        localStorage.setItem(`lastChecked_${userId}`, now.toString());
    }
  },
});